version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./files/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./files/nginx/cert:/root/ssl
      - ../dist/apps/shell:/usr/share/nginx/html
      - ../dist/apps/alarms:/usr/share/nginx/html/feature/alarms
      - ../dist/apps/assets:/usr/share/nginx/html/feature/assets
  api:
    image: node:16-alpine
    ports:
      - '3000:3000'
    volumes:
      - ../dist/apps/fake-api/:/app
      - ./files/fake-api/.env:/app/.env
      - ./files/fake-api/package.json:/app/package.json
    working_dir: /app
    command: /bin/sh -c "npm i && node ./main.js"
  redis:
    image: redis:7-alpine
